### ISSUE TITLE
Fork of Control P5 and rewrite

### ISSUE THREAD

**Issue by poqudrof** [sojamo/controlp5#13]
Hello, 

I spend some time working on a fork of ControlP5 to extend it. I reworked the code architecture to understand how it works and handle the quantity of classes.  
Obviously it is not as convenient now, as it requires multiple import lines in the Processing sketch. 

There are a few new possibilities however : 
- Use another object than the PApplet object to handle the events. 
- Use another PGraphics than the usual  PApplet.g . 
- Rewrite of the mouse / pointer events. There is now a generic "pointer" and the mouse is one of them. Users can add, and remove pointers. 
- Building using Maven. 
- Creation of the library with a Bash script. 
- First reached goal : it works with Ruby with  [JRubyArt](https://github.com/ruby-processing/JRubyArt) (new name of Ruby-Processing). Almost like in Java, the controllers will link to a method, and a variable automatically.  
- Second reached goal : Multiple ControlP5 objects can be instanciated with different graphics contexts (not just different windows). Also, one object can have its own ControlP5 object. 
- Maybe possible : use ControlP5 in Python mode (like we do in Ruby).   
- To come : Extension of the controllers for multi-touch surfaces. 

You can have a look. I kept the name ControlP5 for now. So we have two possibility, try to merge, or I could become real fork with another name. 
Thanks for your great work ! 

Cheers,  

Jeremy.

**Comment by sojamo** [comment]
Hello Jeremy,

thank you for letting me know about your efforts in making adjustments to controlP5 and adding more features. just wondering, did you fork from this ([github](https://github.com/sojamo/controlp5)) repository or from the older code.google repo? the most up-to-date version is this github repository. 

Some of the features you are mentioning, for example the PGraphics context, have been added over time. I haven't looked close enough into the compatibility of controlP5 with other processing implementations like Ruby or Python but there has been some activity and working results with the Python mode.

Browsing through [your repo](https://github.com/potioc/ControlP5) I noticed there was a change in package naming which might be a conflict if merged. The restructuring of the code base had been a consideration a while back but I decided to keep a flat hierarchy to avoid import issues (which package contains which files? which packages do I need to import? etc. this often causes confusion especially for beginners) and also to keep controlP5 backwards compatible. ControlP5 started almost 10 years ago as a small helper library and since did undergo various transformations and has grown quite large (not necessarily to the benefit of the library), introducing a change in structure at this point would be problematic and not a strategy I would like to pursue. 

best,
Andreas
