### ISSUE TITLE
Scrollbar missing from Textarea with few very long lines

### ISSUE THREAD

**Issue by feklee** [sojamo/controlp5#50]
Example:

    import controlP5.*;

    void setup() {
      Textarea ta = new ControlP5(this).addTextarea("");

      for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 100; j++) {
          ta.append("" + i);
        }
        ta.append("\n");
      }
    }

    void draw() {
      background(0);
    }

What I get (Windows 7 x64, Processing 3.0.1):

![Screenshot of Processing window](https://cloud.githubusercontent.com/assets/14994/13027279/c5c9850c-d248-11e5-95be-50de982db977.png)

Scrolling with the mouse wheel also doesn’t work.

**Comment by sojamo** [comment]
the issue here is that the textarea can't separate the input since it cant detect a space or a hyphen to initiate and force a linebreak. It is simply not expected to deal with words of such size. Although you see the 100 zeros split into 4 lines, the textarea considers this as 1 line.  this is why you don't see a scrollbar and hence the mouse wheel wont have any effect in this case. increase the limit for i to 10, you will see a scrollbar, for the given example you need to increase the window size to see the textarea in full size.

**Comment by feklee** [comment]
I would prefer a text area which can smooth scroll, pixel-by-pixel, and which looks at the number of vertical pixels needed when deciding on a scroll-bar. Thing is, some data is without white space, and with very long lines.

Anyhow, even with white space, I don't get a scrollbar. Example code:

    import controlP5.*;
    
    void setup() {
      Textarea ta = new ControlP5(this).addTextarea("");
    
      for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 100; j++) {
          ta.append(" " + i);
        }
        ta.append("\n");
      }
    }
    
    void draw() {
      background(0);
    }

Result:

![Screenshot of text area without scrollbar](https://cloud.githubusercontent.com/assets/14994/13116506/8275298a-d59c-11e5-8409-6dca59e59d09.png)

**Comment by sojamo** [comment]
If I add `size(400,400)` in setup() to your example code the scrollbar becomes visible and I am able to scroll.

**Comment by sojamo** [comment]
no follow up, closing issue.
