### ISSUE TITLE
Interpolate between presets?

### ISSUE THREAD

**Issue by tommypreger** [sojamo/controlp5#59]
Wouldn't it be cool to be able to set a tween time and ease type for all controls in ControlP5? Then you could create a few presets in your sketch and when switching between them you'd get smooth transitions of a set duration. Very useful for doing live visuals.

Or is this maybe already possible?

**Comment by tommypreger** [comment]
I just realised I should have read through the docs a little more carefully before asking. I might as well create ControlListener that do all the actual setting values and do my tweening there.
It might still be a pretty cool feature though. If it was this easy:
cp5.loadProperties(("myCoolPreset.json"), tweenTime, easeType);

**Comment by sojamo** [comment]
for some occasions I have used the [Ani library](http://www.looksgood.de/libraries/Ani/) to tweening between value changes.

**Comment by tommypreger** [comment]
That's exactly what I did after i prematurely posted this. It works like a charm. The only downside is that the sliders themselves aren't tweened, so you don't get any visual feedback from the gui how much "lag" is applied. But that's a minor thing.

Anyway: thank you for a brilliant library! I'm using it to control a live visual set for an upcoming gig and I'm having so much fun programming :)

**Comment by sojamo** [comment]
I have added 2 examples below that demonstrate how to animate and update the slider when tweening. I haven't added any comments inside the code but hope it is clear and self explanatory enough to understand.

the first example uses the listening function `listen(boolean)` that allows controllers to monitor updates made to the variable they are associated with. This method uses reflection, see [controlP5. FieldChangedListener.java](https://github.com/sojamo/controlp5/blob/master/src/controlP5/FieldChangedListener.java)

``` processing
import de.looksgood.ani.*;
import controlP5.*;

ControlP5 cp5;
float a1,a2;

void setup() {
  size(400, 400);
  cp5 = new ControlP5(this);
  cp5.addSlider("a1").setSize(200, 20).setPosition(20, 20).listen(true);
  cp5.addSlider("a2").setSize(200, 20).setPosition(20, 50).listen(true);
  Ani.init(this);
}

void draw() {
  background(a2*2.5);
}

void a1(float v) {
  println("updated a1 to",v);
}

void keyPressed() {
  float duration = 1.5;
  Ani.to( this, duration, "a1", random(0,100), Ani.SINE_IN_OUT);
  Ani.to( this, duration, "a2", random(0,100), Ani.BOUNCE_IN_OUT);
}
```

the second example uses a helper class `Route` which updates the value of a controller according to the tweening associated with it. I prefer this method since it does not required reflection like example 1, though its a bit more code.

``` processing
import de.looksgood.ani.*;
import controlP5.*;

ControlP5 cp5;
float a1,a2;
void setup() {
  size(400, 400);
  cp5 = new ControlP5(this);
  cp5.addSlider("a1").setSize(200, 20).setPosition(20, 20);
  cp5.addSlider("a2").setSize(200, 20).setPosition(20, 50);
  Ani.init(this);
}

void draw() {
  background(a2*2.5);
}

void keyPressed() {
  float duration = 1.5;
  String value = String.format( "value:%f", random(0,100) );
  Ani.to( route( "a1" ), duration, value, Ani.SINE_IN_OUT, "onUpdate:update" );
  Ani.to( route( "a2" ), duration, value, Ani.BOUNCE_IN_OUT, "onUpdate:update" );
}

void a1(float v) {
  println("updated a1 to",v);
}


Route route( String theId ) {
  return new Route( cp5.getController( theId ) );
}

class Route {
  final Controller c;
  float value;

  Route( Controller theController ) {
    c = theController;
    value = c.getValue( );
  }

  void update( ) {
    c.setValue( value );
  }
}


```
